apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: posts-service
build:
  artifacts:
    - image: posts-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: posts-service-mongodb
        remoteChart: mongodb
        version: 10.30.8
        repo: https://charts.bitnami.com/bitnami
        imageStrategy:
          helm: { }
      - name: posts-service
        chartPath: ./posts-service
        artifactOverrides:
          image: posts-service
        setValues:
          kubernetes:
            config:
              name: posts-service-config-map
        imageStrategy:
          helm: { }