apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: posts-service
build:
  artifacts:
    - image: posts-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: posts-service-mongodb
        remoteChart: mongodb
        version: 10.30.8
        repo: https://charts.bitnami.com/bitnami
        wait: true
        setValues:
          persistence:
            enabled: true
          auth:
            enabled: true
            username: "admin"
            rootPassword: "q12345678"
            password: "q12345678"
            database: "admin"
        imageStrategy:
          helm: { }
      - name: posts-service
        chartPath: ./posts-service
        artifactOverrides:
          image: posts-service
        setValues:
          service:
            type: NodePort
          mongodb:
            port: 27017
            host: posts-service-mongodb
            username: root
            password: "q12345678"
            name: admin
        imageStrategy:
          helm: { }