version: 2.1

orbs:
  maven: circleci/maven@1.0.1
jobs:
  build:
    machine: true
    resource_class: small
    steps:
      - checkout

      - maven/with_cache:
          steps:
            - run: mvn clean -q test -x
      - maven/process_test_results
workflows:
  build:
    jobs:
      - build
