version: 2.1

orbs:
  maven: circleci/maven@1.0.1
executors:
  docker-mongo:
    docker:
      - image: circleci/openjdk:14-jdk-buster
      - image: bitnami/mongodb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      spring.data.mongodb.username: root
      spring.data.mongodb.password: "secret"
      spring.data.mongodb.database: "admin"

jobs:
  build:
    executor: docker-mongo
    resource_class: small
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn -q test verify -Pcoverage
      - maven/process_test_results
workflows:
  build:
    jobs:
      - build
