version: 2.1

orbs:
  maven: circleci/maven@1.0.1
executors:
  docker-mongo:
    docker:
      - image: circleci/openjdk:14-jdk-buster
jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - maven/with_cache:
          steps:
            - run: mvn -q test verify -Pcoverage
      - maven/process_test_results
workflows:
  build:
    jobs:
      - build
