version: 2.1

orbs:
  maven: circleci/maven@1.0.1
executors:
  maven-mongodb:
    docker:
      - image: circleci/openjdk:14-jdk-buster
      - image: bitnami/mongodb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      spring.data.mongodb.username: root
      spring.data.mongodb.password: "secret"
      spring.data.mongodb.database: "admin"

jobs:
  test:
    executor: maven-mongodb
    resource_class: small
    steps:
      - checkout
      - maven:
          steps:
            - run: mvn -T 2 clean install
      - persist_to_workspace:
          root: .
          paths:
            - "./target"
      - maven/process_test_results

workflows:
  default:
    jobs:
      - test-and-package
      - push-to-dockerhub:
          filters:
            branches:
              only:
                - main
          requires:
            - test-and-package
