apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "posts-service.fullname" . }}
  labels:
  {{- include "posts-service.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","configmaps"]
    verbs: ["get", "watch", "list"]